DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS repo;
DROP TABLE IF EXISTS assignment;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS note;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS teacher;
DROP TABLE IF EXISTS classroom;
DROP TABLE IF EXISTS organization;

DROP FUNCTION IF EXISTS check_class_teams();
DROP FUNCTION IF EXISTS check_team_members();